---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    apt: # package: generic package manager in ansible
      name:
        - apache2
        - libapache2-mod-php
      update_cache: yes
      state: latest
    when: ansible_distribution == "ubuntu"

  - name: install apache and php for centos servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"



# when: ansible_distribution == "ubuntu" and ansible_distribution_version == "20.04"
# when: ansible_distribution in ["ubuntu", "debian"] # for multiple distros
# when: ansible_distribution == "ubuntu" # for single distros
