- hosts: all
#  vars:
#    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

    - name: create simone user
      tags: always
      user:
        name: simone
        groups: root

    - name: add ssh key for simone
      tags: always
      authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHeCEYD/KV0NbCmm2CgR84LSLJoc0Ru/sqw5FyPEaktd Ansible"

    - name: add sudoers file for simone
      tags: always
      copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: 0440